SELECT TOP (1000) [PayPeriodGenID]
      ,[CompanyRuleID]
      ,[StartDate]
      ,[EndDate]
      ,[TaxYear]
      ,[CalendarYear]
      ,[CalendarMonth]
      ,[PayPeriodInTaxYear]
      ,[PayPeriodsInMonth]
      ,[PayPeriodNumberInMonth]
      ,[PreviousPayPeriodGenID]
      ,[NextPayPeriodGenID]
      ,[CalendarDaysInPeriod]
      ,[WorkDaysInPayPeriod]
      ,[BusinessDaysInPayPeriod]
      ,[PayPeriodsInTaxYear]
      ,[WeeksInMonth]


  FROM [Sage300].[Company].[PayPeriodGen]
